name: CI
on:
  push: {branches: master}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '*.agda'
              - '**/*.agda'
      - uses: omelkonian/setup-agda@master
        if: ${{ steps.changes.outputs.src == 'true' }}
        with:
          agda-version: 2.6.2.1
          stdlib-version: 1.7
          libraries: omelkonian/formal-prelude#67d6
          main: StructuredContracts
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
